//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimientos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculoDepreciacion
    {
        public int Id { get; set; }
        public System.DateTime fechaProceso { get; set; }
        public int montoDepreciado { get; set; }
        public string depreciacionAcumulada { get; set; }
        public int cuentaCompra { get; set; }
        public int cuentaDepreciacon { get; set; }
    }
}
