//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimientos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivosFijosEntities : DbContext
    {
        public ActivosFijosEntities()
            : base("name=ActivosFijosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<ActivoFijo> ActivoFijoes { get; set; }
        public virtual DbSet<CalculoDepreciacion> CalculoDepreciacions { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Estatu> Estatus { get; set; }
        public virtual DbSet<MetodoDepreciacion> MetodoDepreciacions { get; set; }
        public virtual DbSet<Parametro> Parametroes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<TipoActivo> TipoActivoes { get; set; }
        public virtual DbSet<TipoPago> TipoPagoes { get; set; }
        public virtual DbSet<Ubicacion> Ubicacions { get; set; }
    }
}
