//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimientos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int Id { get; set; }
        public int añoProceso { get; set; }
        public int mesProceso { get; set; }
        public string descripcionCalculada { get; set; }
        public int RNC { get; set; }
        public string metodoDepreciacion { get; set; }
    }
}
